/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 van1.gltf --transform 
Files: van1.gltf [563.68KB] > /Users/bishaladhikari/Documents/blenderimg/van/van1-transformed.glb [59.13KB] (90%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/van1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.textured} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_2.geometry} material={materials.firstcolor} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.whiteglass} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/van1-transformed.glb')
